(() => {
'use strict';
const $=id=>document.getElementById(id), books=window.WORDS, KEY='neko-classroom-v1';
const fresh=()=>({seen:[],correct:[],wrong:[],attempts:0,hits:0,daily:{}});
let saved={};try{saved=JSON.parse(localStorage.getItem(KEY)||'{}')||{}}catch{}
let level=['cet4','cet6'].includes(saved.level)?saved.level:'cet4',skin=['pink','summer'].includes(saved.skin)?saved.skin:'classic',records={cet4:{...fresh(),...saved.cet4},cet6:{...fresh(),...saved.cet6}};
for(const k of ['cet4','cet6']){for(const f of ['seen','correct','wrong'])if(!Array.isArray(records[k][f]))records[k][f]=[];if(!records[k].daily||typeof records[k].daily!=='object')records[k].daily={}}
let view='classroom',mode='learn',queue=[],current=null,answered=false,options=[],expression='neutral',answerExpression='neutral',patTimer,page=0;
const day=()=>{const d=new Date();return `${d.getFullYear()}-${d.getMonth()+1}-${d.getDate()}`},state=()=>records[level];
const meaning=w=>w.translations.map(t=>(t.type?t.type+'. ':'')+t.translation).join('；');
const short=w=>{const t=w.translations[0];return (t.type?t.type+'. ':'')+t.translation};
const shuffle=a=>{for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a};
const escape=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function toast(s){$('toast').textContent=s;$('toast').style.display='block';clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('toast').style.display='none',2600)}
function save(){try{localStorage.setItem(KEY,JSON.stringify({...records,level,skin}))}catch{toast('浏览器无法保存记录，本次仍可继续学习。')}}
const skinName={classic:'森系学院',pink:'草莓绒绒',summer:'晴海假日'};
const asset=(s,e='neutral')=>`assets/${s==='classic'?'':s+'-'}${e}.webp`;
function portrait(e){expression=e;$('teacherImage').src=asset(skin,e);$('teacherImage').alt=`${skinName[skin]}小春老师 · ${{neutral:'微笑',happy:'开心',sad:'遗憾',shy:'害羞'}[e]}`}
function say(s){$('dialogueText').textContent=s}
function stats(){const s=state(),today=(s.daily[day()]||[]).length;$('seenCount').textContent=s.seen.length;$('masteredCount').textContent=s.correct.length;$('reviewCount').textContent=s.wrong.length;$('wrongBadge').textContent=s.wrong.length;$('accuracy').textContent=s.attempts?Math.round(s.hits/s.attempts*100)+'%':'—';$('dailyCount').textContent=`${today} / 20`;$('progressBar').style.width=Math.min(100,today/20*100)+'%';$('lessonCounter').textContent=`${String(today).padStart(2,'0')} / 20`;document.querySelectorAll('[data-level]').forEach(b=>b.classList.toggle('active',b.dataset.level===level))}
function makeQueue(){const s=state();queue=shuffle(books[level].filter(w=>mode==='review'?s.wrong.includes(w.word):!s.seen.includes(w.word)));if(!queue.length&&mode==='learn')queue=shuffle([...books[level]])}
function next(){clearTimeout(patTimer);if(!queue.length)makeQueue();current=queue.pop();answered=false;portrait('neutral');$('next').hidden=true;$('skip').hidden=false;$('feedback').textContent='';$('lessonLabel').textContent=`${level==='cet4'?'CET-4':'CET-6'} · ${mode==='review'?'错题复习':'词义练习'}`;
if(!current){$('word').textContent='复习完成 ✧';$('phonetic').textContent='';$('options').replaceChildren();$('skip').hidden=true;say('错题已经全部复习完啦！回到学习教室继续前进吧。');return}
$('word').textContent=current.word;$('phonetic').textContent=current.uk?`/${current.uk}/`:current.us?`/${current.us}/`:'听听发音';
const distractors=shuffle([...books[level]]).filter(w=>w.word!==current.word&&short(w)!==short(current));const distinct=[];for(const w of distractors){if(!distinct.some(x=>short(x)===short(w)))distinct.push(w);if(distinct.length===3)break}options=shuffle([current,...distinct]);
$('options').replaceChildren(...options.map((w,i)=>{const b=document.createElement('button');b.className='option';b.innerHTML=`<b>${'ABCD'[i]}</b><span>${escape(short(w))}</span>`;b.onclick=()=>answer(i);return b}));say(mode==='review'?'再见面就更熟悉了。我们把这个词记牢吧。':'不着急，想一想。每一个单词都是一点进步。');stats()}
function answer(index){if(answered||!current)return;clearTimeout(patTimer);answered=true;const right=index>=0&&options[index].word===current.word,s=state();s.attempts++;if(right)s.hits++;if(!s.seen.includes(current.word))s.seen.push(current.word);if(!Array.isArray(s.daily[day()]))s.daily[day()]=[];if(!s.daily[day()].includes(current.word))s.daily[day()].push(current.word);
if(right){if(!s.correct.includes(current.word))s.correct.push(current.word);s.wrong=s.wrong.filter(w=>w!==current.word)}else{s.correct=s.correct.filter(w=>w!==current.word);if(!s.wrong.includes(current.word))s.wrong.push(current.word)}
document.querySelectorAll('.option').forEach((b,i)=>{b.disabled=true;if(options[i].word===current.word)b.classList.add('correct');else if(i===index)b.classList.add('wrong')});
const example=current.sentences?.[0];$('feedback').innerHTML=`<strong>${right?'✓ 答对啦':'↺ 已记入错题本'}</strong> · ${escape(meaning(current))}${example?`<br>${escape(example.sentence)}<br>${escape(example.translation)}`:''}`;answerExpression=right?'happy':'sad';portrait(answerExpression);say(right?'答对啦！你认真思考的样子，老师很喜欢喵。':'有一点可惜，不过没关系。把这次相遇记住，下次就会啦。');$('skip').hidden=true;$('next').hidden=false;stats();save()}
function setView(v){view=v;document.querySelectorAll('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===v));$('classroom').hidden=v!=='classroom';$('library').hidden=v==='classroom';if(v!=='classroom'){page=0;$('search').value='';renderList()}else{mode='learn';makeQueue();next()}}
function renderList(){const wrong=view==='mistakes',q=$('search').value.trim().toLowerCase();const list=books[level].filter(w=>(!wrong||state().wrong.includes(w.word))&&(!q||w.word.toLowerCase().includes(q)||meaning(w).toLowerCase().includes(q)));const pages=Math.max(1,Math.ceil(list.length/20));page=Math.max(0,Math.min(page,pages-1));$('collectionTitle').textContent=wrong?'把遗憾，变成下一次的答对。':'你的单词图书馆';$('collectionInfo').textContent=`${level.toUpperCase()} · ${wrong?'待复习':'收录'} ${list.length.toLocaleString()} 词${q?' · 搜索结果':''}`;$('startReview').hidden=!wrong||!state().wrong.length;
$('wordList').innerHTML=list.slice(page*20,page*20+20).map(w=>`<article class="word-row"><div><strong>${escape(w.word)}</strong><small>${escape(w.uk||w.us||'')}${state().correct.includes(w.word)?' · ✓ 已答对':''}</small></div><p>${escape(meaning(w))}</p><button data-word="${escape(w.word)}">练习 →</button></article>`).join('')||'<div class="empty">✧<p>这里暂时没有单词。'+(q?'换个关键词试试。':'继续学习，慢慢积攒进步吧。')+'</p></div>';
$('pageInfo').textContent=`${page+1} / ${pages}`;$('prevPage').disabled=page===0;$('nextPage').disabled=page>=pages-1;$('wordList').querySelectorAll('[data-word]').forEach(b=>b.onclick=()=>{const w=books[level].find(w=>w.word===b.dataset.word);view='classroom';$('library').hidden=true;$('classroom').hidden=false;document.querySelectorAll('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view==='classroom'));mode=wrong?'review':'learn';queue=[w];next();window.scrollTo({top:0,behavior:'smooth'})})}
document.querySelectorAll('[data-level]').forEach(b=>b.onclick=()=>{if(level===b.dataset.level)return;level=b.dataset.level;mode='learn';queue=[];stats();save();if(view==='classroom'){makeQueue();next()}else{page=0;renderList()}});
document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>setView(b.dataset.view));$('next').onclick=next;$('skip').onclick=()=>answer(-1);$('search').oninput=()=>{page=0;renderList()};$('prevPage').onclick=()=>{page--;renderList()};$('nextPage').onclick=()=>{page++;renderList()};$('startReview').onclick=()=>{setView('classroom');mode='review';makeQueue();next()};
$('teacher').onclick=()=>{clearTimeout(patTimer);portrait('shy');say('呜…耳朵有点敏感啦。再摸一下，就要认真背单词了喵。');$('hearts').textContent='♡';$('hearts').classList.remove('pop');void $('hearts').offsetWidth;$('hearts').classList.add('pop');patTimer=setTimeout(()=>{portrait(answered?answerExpression:'neutral');say(answered?'复习好释义，再一起看下一个词吧。':'好啦，让我们回到黑板上的单词吧。')},3200)};
$('speak').onclick=()=>{if(!current)return;if(!('speechSynthesis'in window)){toast('此浏览器不支持朗读，请查看音标。');return}speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(current.word);u.lang='en-US';u.rate=.8;u.onerror=()=>toast('设备语音暂不可用，请查看音标。');speechSynthesis.speak(u)};
function skinApply(){document.body.classList.toggle('pink',skin==='pink');document.body.classList.toggle('summer',skin==='summer');document.body.dataset.skin=skin;portrait(expression);document.querySelectorAll('button[data-skin]').forEach(b=>b.classList.toggle('selected',b.dataset.skin===skin))}
$('wardrobe').onclick=()=>{$('skinDialog').showModal();skinApply()};document.querySelectorAll('button[data-skin]').forEach(b=>b.onclick=()=>{skin=b.dataset.skin;skinApply();save();$('skinDialog').close();say(skin==='pink'?'换上软乎乎的猫爪手套啦。今天也暖暖地学习吧。':skin==='summer'?'海风刚刚好，和老师一起开启今天的词课吧。':'经典的学院装扮，准备上课喵。')});$('sourceButton').onclick=()=>$('sourceDialog').showModal();document.querySelectorAll('dialog .close').forEach(b=>b.onclick=()=>b.closest('dialog').close());document.querySelectorAll('dialog').forEach(d=>d.onclick=e=>{if(e.target===d){const r=d.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)d.close()}});
document.addEventListener('keydown',e=>{if(/INPUT|TEXTAREA/.test(e.target.tagName)||document.querySelector('dialog[open]')||view!=='classroom')return;if(['1','2','3','4'].includes(e.key)&&!answered)answer(Number(e.key)-1);if(e.key==='Enter'&&answered&&e.target===document.body){e.preventDefault();next()}});
function galleryMode(crop){$('galleryStage').classList.toggle('cropped',crop);$('fullView').classList.toggle('active',!crop);$('cropView').classList.toggle('active',crop);$('galleryImage').src=skin==='classic'?(crop?asset(skin):'assets/classic-full.webp'):asset(skin);$('galleryStage').dataset.skin=skin;}
$('galleryButton').onclick=()=>{$('galleryTitle').textContent=skinName[skin]+' · 小春';galleryMode(false);$('galleryDialog').showModal()};$('fullView').onclick=()=>galleryMode(false);$('cropView').onclick=()=>galleryMode(true);
skinApply();stats();makeQueue();next();
})();



