(() => {
'use strict';
const $=id=>document.getElementById(id), books=window.WORDS, KEY='neko-classroom-v1';
const fresh=()=>({seen:[],correct:[],wrong:[],attempts:0,hits:0,daily:{},listeningSeen:[],listeningWrong:[],listeningAttempts:0,listeningHits:0});
let saved={};try{saved=JSON.parse(localStorage.getItem(KEY)||'{}')||{}}catch{}
const extraSkins=['laceblack','mintlace','candy','burgundy'];
let level=['cet4','cet6'].includes(saved.level)?saved.level:'cet4',skin=['pink','summer','scut','noir','crimson','ivory','amethyst','maid',...extraSkins].includes(saved.skin)?saved.skin:'classic',records={cet4:{...fresh(),...saved.cet4},cet6:{...fresh(),...saved.cet6}};
for(const k of ['cet4','cet6']){for(const f of ['seen','correct','wrong','listeningSeen','listeningWrong'])if(!Array.isArray(records[k][f]))records[k][f]=[];if(!records[k].daily||typeof records[k].daily!=='object')records[k].daily={};records[k].listeningAttempts=Number(records[k].listeningAttempts)||0;records[k].listeningHits=Number(records[k].listeningHits)||0}
let view='classroom',mode='learn',queue=[],current=null,answered=false,options=[],expression='neutral',answerExpression='neutral',patTimer,page=0,listenQueue=[],listenCurrent=null,listenSample=null,listenOptions=[],listenAnswer='',listenAnswered=false,listenMode='meaning',listenReview=false,listenNumber=0;
const day=()=>{const d=new Date();return `${d.getFullYear()}-${d.getMonth()+1}-${d.getDate()}`},state=()=>records[level];
const meaning=w=>w.translations.map(t=>(t.type?t.type+'. ':'')+t.translation).join('；');
const short=w=>{const t=w.translations[0];return (t.type?t.type+'. ':'')+t.translation};
const shuffle=a=>{for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a};
const escape=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function toast(s){$('toast').textContent=s;$('toast').style.display='block';clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('toast').style.display='none',2600)}
function save(){try{localStorage.setItem(KEY,JSON.stringify({...records,level,skin}))}catch{toast('浏览器无法保存记录，本次仍可继续学习。')}}
const skinName={classic:'森系学院',pink:'草莓绒绒',summer:'晴海假日',noir:'夜猫黑丝',crimson:'绯夜猫铃',ivory:'白昼恋歌',amethyst:'紫罗兰韵',maid:'月夜女仆',scut:'特别校服',laceblack:'黑曜蕾影',mintlace:'薄荷蕾丝',candy:'糖果缎带',burgundy:'酒红夜曲'};
function asset(s,e='neutral'){if(extraSkins.includes(s))return`assets/${s}-${e}.png`;if(s==='noir'&&['neutral','affection'].includes(e))return`assets/noir-${e}-v2.png`;if(['scut','noir','crimson','ivory','amethyst','maid'].includes(s))return`assets/${s}-${e}.png`;if(['affection','disdain'].includes(e))return`assets/${s==='classic'?'classic':s}-${e}.png`;return`assets/${s==='classic'?'':s+'-'}${e}.webp`}
function bondMood(){const v=window.NekoModules?.affection?.()??45;return v<20?'disdain':v>=70?'affection':'neutral'}
function bondTier(){const v=window.NekoModules?.affection?.()??45;return v<20?0:v<40?1:v<70?2:v<90?3:4}
const teacherLines={
 prompt:['还要我等多久？选一个答案。','先认真看题。答对了，我会承认你有进步。','慢慢想，老师会陪你把这个词弄懂。','答对的话，下课后可以再陪老师一会儿哦。','这道题答完就坐近一点，我只讲给你听。'],
 review:['又错过的词？这次别再让我失望。','把上次没记住的补回来，我在看着。','再见面就会更熟悉，我们把它记牢吧。','认真复习完，老师给你一点小奖励。','你忘掉的部分都交给我，今天陪你全部补回来。'],
 correct:['至少这一次没有让我失望。','嗯，答对了，勉强值得表扬。','答对啦！你认真思考的样子很可爱。','真棒。看见你进步，老师比你还开心。','答得这么好……让我越来越舍不得结束这节课了。'],
 wrong:['果然分心了。把答案看清楚再继续。','可惜。下次别再错同一个词。','没关系，遗憾一次才会记得更牢。','错了也不许躲，靠近一点，我重新讲给你听。','笨一点也没关系，我会一直教到你记住为止。'],
 pat:['别碰我的耳朵，先把手收回去。','耳朵很敏感……摸一下就够了。','呜……突然摸过来，老师会害羞的。','再摸一下的话，老师可就没办法专心讲课了。','只有你可以这样摸……但要多陪我一会儿。'],
 resume:['手收回去，看黑板。','好了，继续上课。','好啦，我们回到黑板上的单词吧。','耳朵还在发热……下一题要认真答哦。','先继续上课，等结束以后再让你靠近一点。'],
 resumeAnswered:['把释义记住，别只顾着看我。','复习好释义，再看下一题。','把这个词收好，我们一起看下一个。','老师还想再看你答对一次。','下一题也答对的话，我会再夸你一次。'],
 complete:['复习完了。今天还算认真。','错题清空了，进步值得肯定。','全部复习完成，老师很为你高兴。','都记住了？那就留下来陪老师聊一会儿吧。','今天的课程结束了，但我还不想让你走。']
};
function teacherLine(kind){return teacherLines[kind]?.[bondTier()]||''}
const skinLines={classic:'经典学院装换好了。',pink:'软乎乎的猫爪手套戴好了。',summer:'今天换成晴海假日。',scut:'特别校服换好了，纪念帆布包也带来了。',noir:'夜猫黑丝已经换好了。',crimson:'绯夜猫铃已经换好了。',ivory:'今天是白昼恋歌。',amethyst:'灰紫旗袍和披肩已经换好了。',maid:'今天由女仆老师负责课程。',laceblack:'黑曜蕾影换好了。',mintlace:'薄荷蕾丝换好了。',candy:'糖果缎带换好了。',burgundy:'今天换成酒红夜曲。'};
const skinSuffix=['只是上课需要，别想太多。','看够了就开始学习。','你喜欢的话，我可以多穿一会儿。','你一直看着，老师也会不好意思的。','既然是你选的，今天就只穿给你看。'];
function skinLine(s){return`${skinLines[s]||''}${skinSuffix[bondTier()]}`}
function portrait(e){expression=e;const shown=e==='neutral'?bondMood():e;document.body.dataset.expression=shown;$('teacherImage').src=asset(skin,shown);$('teacherImage').alt=`${skinName[skin]}小春老师 · ${{neutral:'微笑',happy:'开心',sad:'遗憾',shy:'害羞',affection:'亲昵',disdain:'挑逗式嫌弃'}[shown]}`}
function say(s){$('dialogueText').textContent=s}
function stats(){const s=state(),today=(s.daily[day()]||[]).length,l=s;$('seenCount').textContent=s.seen.length;$('masteredCount').textContent=s.correct.length;$('reviewCount').textContent=s.wrong.length;$('wrongBadge').textContent=s.wrong.length;$('listenBadge').textContent=l.listeningWrong.length;$('listenWrongCount').textContent=l.listeningWrong.length;$('listenDone').textContent=l.listeningSeen.length;$('listenWrong').textContent=l.listeningWrong.length;$('listenAccuracy').textContent=l.listeningAttempts?Math.round(l.listeningHits/l.listeningAttempts*100)+'%':'—';$('accuracy').textContent=s.attempts?Math.round(s.hits/s.attempts*100)+'%':'—';$('dailyCount').textContent=`${today} / 20`;$('progressBar').style.width=Math.min(100,today/20*100)+'%';$('lessonCounter').textContent=`${String(today).padStart(2,'0')} / 20`;document.querySelectorAll('[data-level]').forEach(b=>b.classList.toggle('active',b.dataset.level===level))}
function makeQueue(){const s=state();queue=shuffle(books[level].filter(w=>mode==='review'?s.wrong.includes(w.word):!s.seen.includes(w.word)));if(!queue.length&&mode==='learn')queue=shuffle([...books[level]])}
function next(){clearTimeout(patTimer);if(!queue.length)makeQueue();current=queue.pop();answered=false;portrait('neutral');$('next').hidden=true;$('skip').hidden=false;$('feedback').textContent='';$('lessonLabel').textContent=`${level==='cet4'?'CET-4':'CET-6'} · ${mode==='review'?'错题复习':'词义练习'}`;
if(!current){$('word').textContent='复习完成 ✧';$('phonetic').textContent='';$('options').replaceChildren();$('skip').hidden=true;say(teacherLine('complete'));return}
$('word').textContent=current.word;$('phonetic').textContent=current.uk?`/${current.uk}/`:current.us?`/${current.us}/`:'听听发音';
const distractors=shuffle([...books[level]]).filter(w=>w.word!==current.word&&short(w)!==short(current));const distinct=[];for(const w of distractors){if(!distinct.some(x=>short(x)===short(w)))distinct.push(w);if(distinct.length===3)break}options=shuffle([current,...distinct]);
$('options').replaceChildren(...options.map((w,i)=>{const b=document.createElement('button');b.className='option';b.innerHTML=`<b>${'ABCD'[i]}</b><span>${escape(short(w))}</span>`;b.onclick=()=>answer(i);return b}));say(teacherLine(mode==='review'?'review':'prompt'));stats()}
function answer(index){if(answered||!current)return;clearTimeout(patTimer);answered=true;const right=index>=0&&options[index].word===current.word,s=state();s.attempts++;if(right)s.hits++;if(!s.seen.includes(current.word))s.seen.push(current.word);if(!Array.isArray(s.daily[day()]))s.daily[day()]=[];if(!s.daily[day()].includes(current.word))s.daily[day()].push(current.word);
if(right){if(!s.correct.includes(current.word))s.correct.push(current.word);s.wrong=s.wrong.filter(w=>w!==current.word)}else{s.correct=s.correct.filter(w=>w!==current.word);if(!s.wrong.includes(current.word))s.wrong.push(current.word)}
document.querySelectorAll('.option').forEach((b,i)=>{b.disabled=true;if(options[i].word===current.word)b.classList.add('correct');else if(i===index)b.classList.add('wrong')});
const example=current.sentences?.[0];$('feedback').innerHTML=`<strong>${right?'✓ 答对啦':'↺ 已记入错题本'}</strong> · ${escape(meaning(current))}${example?`<br>${escape(example.sentence)}<br>${escape(example.translation)}`:''}`;answerExpression=right?'happy':'sad';portrait(answerExpression);window.NekoModules?.changeBond(right?2:-1,right?'认真答对单词':'单词答错');say(teacherLine(right?'correct':'wrong'));$('skip').hidden=true;$('next').hidden=false;stats();save()}
function setView(v){view=v;document.querySelectorAll('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===v));$('classroom').hidden=v!=='classroom';$('listening').hidden=v!=='listening';$('practice').hidden=v!=='practice';$('bond').hidden=v!=='bond';$('library').hidden=!['library','mistakes'].includes(v);if(v==='listening'){listenQueue=[];listenCurrent=null;listenReview=false;listenNumber=0;stats();nextListening()}else if(['library','mistakes'].includes(v)){page=0;$('search').value='';renderList()}else if(v==='classroom'){mode='learn';makeQueue();next()}window.NekoModules?.open(v,level)}
function renderList(){const wrong=view==='mistakes',q=$('search').value.trim().toLowerCase();const list=books[level].filter(w=>(!wrong||state().wrong.includes(w.word))&&(!q||w.word.toLowerCase().includes(q)||meaning(w).toLowerCase().includes(q)));const pages=Math.max(1,Math.ceil(list.length/20));page=Math.max(0,Math.min(page,pages-1));$('collectionTitle').textContent=wrong?'把遗憾，变成下一次的答对。':'你的单词图书馆';$('collectionInfo').textContent=`${level.toUpperCase()} · ${wrong?'待复习':'收录'} ${list.length.toLocaleString()} 词${q?' · 搜索结果':''}`;$('startReview').hidden=!wrong||!state().wrong.length;
$('wordList').innerHTML=list.slice(page*20,page*20+20).map(w=>`<article class="word-row"><div><strong>${escape(w.word)}</strong><small>${escape(w.uk||w.us||'')}${state().correct.includes(w.word)?' · ✓ 已答对':''}</small></div><p>${escape(meaning(w))}</p><button data-word="${escape(w.word)}">练习 →</button></article>`).join('')||'<div class="empty">✧<p>这里暂时没有单词。'+(q?'换个关键词试试。':'继续学习，慢慢积攒进步吧。')+'</p></div>';
$('pageInfo').textContent=`${page+1} / ${pages}`;$('prevPage').disabled=page===0;$('nextPage').disabled=page>=pages-1;$('wordList').querySelectorAll('[data-word]').forEach(b=>b.onclick=()=>{const w=books[level].find(w=>w.word===b.dataset.word);view='classroom';$('library').hidden=true;$('classroom').hidden=false;document.querySelectorAll('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view==='classroom'));mode=wrong?'review':'learn';queue=[w];next();window.scrollTo({top:0,behavior:'smooth'})})}
function listeningPool(){return books[level].filter(w=>Array.isArray(w.sentences)&&w.sentences.some(s=>s.sentence&&s.translation&&(listenMode==='meaning'||new RegExp(`\\b${w.word.replace(/[.*+?^${}()|[\\]\\\\]/g,'\\$&')}\\b`,'i').test(s.sentence))))}
function nextListening(){if('speechSynthesis'in window)speechSynthesis.cancel();const pool=listeningPool(),s=state();if(!listenQueue.length){const source=listenReview?pool.filter(w=>s.listeningWrong.includes(w.word)):pool.filter(w=>!s.listeningSeen.includes(w.word));listenQueue=shuffle(source.length?source:[...pool])}listenCurrent=listenQueue.pop()||null;listenAnswered=false;listenNumber++;$('nextListening').hidden=true;$('listenFeedback').textContent='';$('listenTranscript').hidden=true;$('revealTranscript').textContent='显示原文';$('listeningEyebrow').textContent=`${level.toUpperCase()} · LISTENING STUDIO`;$('listeningTitle').textContent=`${level==='cet4'?'四级':'六级'}听力训练室`;$('listenType').textContent=listenReview?'错题重练':listenMode==='meaning'?'句意理解':'关键词听辨';$('listenProgress').textContent=`第 ${listenNumber} 题`;document.querySelectorAll('[data-listen-mode]').forEach(b=>b.classList.toggle('active',b.dataset.listenMode===listenMode));
if(!listenCurrent){$('listenPrompt').textContent='当前没有可练习的听力错题';$('listenOptions').replaceChildren();$('listenQuestion').textContent='先完成一些听力题，再回来重练吧。';return}
const samples=listenCurrent.sentences.filter(x=>x.sentence&&x.translation&&(listenMode==='meaning'||new RegExp(`\\b${listenCurrent.word.replace(/[.*+?^${}()|[\\]\\\\]/g,'\\$&')}\\b`,'i').test(x.sentence)));listenSample=samples[Math.floor(Math.random()*samples.length)];$('listenPrompt').textContent='点击播放，听两遍句子';$('listenHint').textContent=level==='cet4'?'四级：注意高频词、数字和句子主旨。':'六级：注意同义替换、语气和长句细节。';$('listenQuestion').textContent=listenMode==='meaning'?'请选择你听到的句子表达的中文意思':'请选择句子中出现的关键词';
if(listenMode==='meaning'){listenAnswer=listenSample.translation;const maxGap=Math.max(8,Math.ceil(listenAnswer.length*.8));const candidates=pool.filter(w=>w.word!==listenCurrent.word).flatMap(w=>w.sentences.map(x=>x.translation)).filter(x=>x&&x.length>=5&&Math.abs(x.length-listenAnswer.length)<=maxGap);const fallback=pool.filter(w=>w.word!==listenCurrent.word).flatMap(w=>w.sentences.map(x=>x.translation)).filter(Boolean);listenOptions=[listenAnswer];for(const x of shuffle([...candidates,...fallback])){if(!listenOptions.includes(x))listenOptions.push(x);if(listenOptions.length===4)break}}else{listenAnswer=listenCurrent.word;listenOptions=[listenAnswer];for(const w of shuffle(pool.filter(w=>w.word!==listenCurrent.word))){if(!listenOptions.includes(w.word))listenOptions.push(w.word);if(listenOptions.length===4)break}}shuffle(listenOptions);$('listenOptions').replaceChildren(...listenOptions.map((text,i)=>{const b=document.createElement('button');b.className='listen-option';b.innerHTML=`<b>${'ABCD'[i]}</b><span>${escape(text)}</span>`;b.onclick=()=>answerListening(i);return b}));stats()}
function playSentence(times=1){if(!listenSample)return;if(!('speechSynthesis'in window)){toast('此设备暂不支持语音播放，已为你显示原文。');$('listenTranscript').hidden=false;return}speechSynthesis.cancel();$('waveform').classList.add('playing');for(let i=0;i<times;i++){const u=new SpeechSynthesisUtterance(listenSample.sentence);u.lang='en-US';u.rate=Number($('listenRate').value);u.pitch=1;u.onend=()=>{if(i===times-1)$('waveform').classList.remove('playing')};u.onerror=()=>{$('waveform').classList.remove('playing');toast('设备语音暂不可用，可以显示原文继续练习。')};speechSynthesis.speak(u)}}
function answerListening(index){if(listenAnswered||!listenCurrent)return;listenAnswered=true;const picked=listenOptions[index],right=picked===listenAnswer,s=state();s.listeningAttempts++;if(right)s.listeningHits++;if(!s.listeningSeen.includes(listenCurrent.word))s.listeningSeen.push(listenCurrent.word);if(right)s.listeningWrong=s.listeningWrong.filter(w=>w!==listenCurrent.word);else if(!s.listeningWrong.includes(listenCurrent.word))s.listeningWrong.push(listenCurrent.word);document.querySelectorAll('.listen-option').forEach((b,i)=>{b.disabled=true;if(listenOptions[i]===listenAnswer)b.classList.add('correct');else if(i===index)b.classList.add('wrong')});$('listenTranscript').hidden=false;$('listenTranscript').innerHTML=`<strong>原文</strong> ${escape(listenSample.sentence)}<br><strong>译文</strong> ${escape(listenSample.translation)}`;$('listenFeedback').innerHTML=right?'<strong>✓ 听对啦</strong> · 抓住了句子的关键信息。':'<strong>↺ 已加入听力错题</strong> · 对照原文再听一次，注意加粗的答案。';$('nextListening').hidden=false;window.NekoModules?.changeBond(right?2:-1,right?'听力答对':'听力答错');save();stats()}
document.querySelectorAll('[data-level]').forEach(b=>b.onclick=()=>{if(level===b.dataset.level)return;level=b.dataset.level;mode='learn';queue=[];listenQueue=[];listenCurrent=null;listenNumber=0;stats();save();if(view==='listening'){listenReview=false;nextListening()}else if(view==='classroom'){makeQueue();next()}else if(['library','mistakes'].includes(view)){page=0;renderList()}window.NekoModules?.open(view,level)});
document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>setView(b.dataset.view));$('next').onclick=next;$('skip').onclick=()=>answer(-1);$('search').oninput=()=>{page=0;renderList()};$('prevPage').onclick=()=>{page--;renderList()};$('nextPage').onclick=()=>{page++;renderList()};$('startReview').onclick=()=>{setView('classroom');mode='review';makeQueue();next()};
$('playListening').onclick=()=>playSentence(2);$('replayListening').onclick=()=>playSentence(1);$('nextListening').onclick=nextListening;$('revealTranscript').onclick=()=>{if(!listenSample)return;const show=$('listenTranscript').hidden;$('listenTranscript').hidden=!show;$('revealTranscript').textContent=show?'隐藏原文':'显示原文';if(show)$('listenTranscript').innerHTML=`<strong>原文</strong> ${escape(listenSample.sentence)}${listenAnswered?`<br><strong>译文</strong> ${escape(listenSample.translation)}`:''}`};$('reviewListening').onclick=()=>{if(!state().listeningWrong.length){toast('当前级别还没有听力错题。');return}listenReview=true;listenQueue=[];listenCurrent=null;listenNumber=0;nextListening()};document.querySelectorAll('[data-listen-mode]').forEach(b=>b.onclick=()=>{listenMode=b.dataset.listenMode;listenReview=false;listenQueue=[];listenCurrent=null;listenNumber=0;nextListening()});
$('teacher').onclick=()=>{clearTimeout(patTimer);portrait('shy');say(teacherLine('pat'));$('hearts').textContent='♡';$('hearts').classList.remove('pop');void $('hearts').offsetWidth;$('hearts').classList.add('pop');patTimer=setTimeout(()=>{portrait(answered?answerExpression:'neutral');say(teacherLine(answered?'resumeAnswered':'resume'))},3200)};
$('speak').onclick=()=>{if(!current)return;if(!('speechSynthesis'in window)){toast('此浏览器不支持朗读，请查看音标。');return}speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(current.word);u.lang='en-US';u.rate=.8;u.onerror=()=>toast('设备语音暂不可用，请查看音标。');speechSynthesis.speak(u)};
function skinApply(){if(!window.NekoModules?.unlocked(skin))skin='classic';for(const c of ['pink','summer','scut','noir','crimson','ivory','amethyst','maid',...extraSkins])document.body.classList.toggle(c,skin===c);document.body.dataset.skin=skin;portrait(expression);document.querySelectorAll('button[data-skin]').forEach(b=>{b.classList.toggle('selected',b.dataset.skin===skin);b.classList.toggle('locked',!window.NekoModules?.unlocked(b.dataset.skin));const lock=b.querySelector('.skin-lock');if(lock)lock.hidden=window.NekoModules?.unlocked(b.dataset.skin)});window.dispatchEvent(new CustomEvent('neko-skin',{detail:{skin}}))}
$('wardrobe').onclick=()=>{$('skinDialog').showModal();skinApply()};document.querySelectorAll('button[data-skin]').forEach(b=>b.onclick=()=>{if(!window.NekoModules?.unlocked(b.dataset.skin)){toast(b.dataset.skin==='scut'?'请先在衣橱上方输入兑换码领取特别校服。':'这套限定衣装需要在小春养成中选择解锁。');return}skin=b.dataset.skin;skinApply();save();$('skinDialog').close();say(skinLine(skin))});$('sourceButton').onclick=()=>$('sourceDialog').showModal();document.querySelectorAll('dialog .close').forEach(b=>b.onclick=()=>b.closest('dialog').close());document.querySelectorAll('dialog').forEach(d=>d.onclick=e=>{if(e.target===d){const r=d.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)d.close()}});
document.addEventListener('keydown',e=>{if(/INPUT|TEXTAREA|SELECT/.test(e.target.tagName)||document.querySelector('dialog[open]'))return;if(view==='classroom'){if(['1','2','3','4'].includes(e.key)&&!answered)answer(Number(e.key)-1);if(e.key==='Enter'&&answered&&e.target===document.body){e.preventDefault();next()}}else if(view==='listening'){if(e.code==='Space'){e.preventDefault();playSentence(1)}if(['1','2','3','4'].includes(e.key)&&!listenAnswered)answerListening(Number(e.key)-1);if(e.key==='Enter'&&listenAnswered)nextListening()}});
function galleryMode(crop){$('galleryStage').classList.toggle('cropped',crop);$('fullView').classList.toggle('active',!crop);$('cropView').classList.toggle('active',crop);$('galleryImage').src=skin==='classic'?(crop?asset(skin):'assets/classic-full.webp'):skin==='noir'?'assets/noir-neutral.png':extraSkins.includes(skin)&&!crop?`assets/${skin}-full.png`:asset(skin);$('galleryStage').dataset.skin=skin;}
$('galleryButton').onclick=()=>{$('galleryTitle').textContent=skinName[skin]+' · 小春';galleryMode(false);$('galleryDialog').showModal()};$('fullView').onclick=()=>galleryMode(false);$('cropView').onclick=()=>galleryMode(true);
window.addEventListener('neko-affection',()=>{document.body.classList.toggle('bond-high',bondMood()==='affection');document.body.classList.toggle('bond-low',bondMood()==='disdain');portrait(answered?answerExpression:'neutral');skinApply()});window.addEventListener('neko-unlock',e=>{skinApply();toast(e.detail?.developer?'开发者模式已开启，全部衣装可用。':'限定衣装已永久加入老师的衣橱。')});skinApply();document.body.classList.toggle('bond-high',bondMood()==='affection');document.body.classList.toggle('bond-low',bondMood()==='disdain');stats();makeQueue();next();
})();



