(() => {
'use strict';
const $=id=>document.getElementById(id),KEY='neko-companion-v1',books=window.WORDS;
const today=()=>new Date().toLocaleDateString('zh-CN'),clamp=n=>Math.max(0,Math.min(100,n));
const blank=()=>({bond:45,actionDay:today(),actionsUsed:0,practice:{cet4:0,cet6:0},logs:[],unlockedSkins:[],claimedMilestones:[]});
let data=blank();try{data={...data,...JSON.parse(localStorage.getItem(KEY)||'{}')}}catch{}
if(!data.practice||typeof data.practice!=='object')data.practice={cet4:0,cet6:0};if(!Array.isArray(data.unlockedSkins))data.unlockedSkins=[];if(!Array.isArray(data.claimedMilestones))data.claimedMilestones=[];
if(data.actionDay!==today()){data.actionDay=today();data.actionsUsed=0}
let level='cet4',mode='reading',question=null,answered=false,timerStart=Date.now(),timerId;
const extraSkins=['laceblack','mintlace','candy','burgundy'];
const rewardSkins={noir:'夜猫黑丝',crimson:'绯夜猫铃',ivory:'白昼恋歌',amethyst:'紫罗兰韵',maid:'月夜女仆',laceblack:'黑曜蕾影',mintlace:'薄荷蕾丝',candy:'糖果缎带',burgundy:'酒红夜曲'},allSkinNames={...rewardSkins,scut:'特别校服'},bondSkins={pink:'assets/pink-bond-v1.png',summer:'assets/summer-bond-v2.png',noir:'assets/noir-bond-v1.png',ivory:'assets/ivory-bond-v1.png'},milestones=[70,80,90,95];
const writing={
 cet4:[
  ['校园生活','Write about one habit that makes college life more productive. Give reasons and an example.'],
  ['科技与学习','Write about the proper use of AI tools in college learning.'],
  ['社会责任','Write about a small action young people can take to protect the environment.'],
  ['个人成长','Write about a challenge that taught you an important lesson.']
 ],
 cet6:[
  ['数字时代的专注力','Discuss why sustained attention matters in the digital age and how students can protect it.'],
  ['教育与实践','Discuss whether practical experience should play a larger role in university education.'],
  ['文化传播','Explain how young people can introduce Chinese culture effectively to an international audience.'],
  ['选择与责任','Discuss the relationship between personal choice and social responsibility.']
 ]
};
function save(){localStorage.setItem(KEY,JSON.stringify(data))}
function stage(v=data.bond){return v<20?['冷淡','她正用挑剔的目光审视你。']:v<40?['生疏','关系有点僵，认真学习能慢慢挽回。']:v<70?['渐渐熟悉','她已经开始期待你的到来。']:v<90?['心动','她看你的眼神变得格外亲昵。']:['特别关系','下课以后，她只想多留你一会儿。']}
function mood(v=data.bond){return v<20?'disdain':v>=70?'affection':'neutral'}
function asset(s,e=mood()){if(extraSkins.includes(s))return`assets/${s}-${e}.png?v=2`;if(s==='noir'&&['neutral','affection'].includes(e))return`assets/noir-${e}-v2.png`;if(['scut','noir','crimson','ivory','amethyst','maid'].includes(s))return`assets/${s}-${e}.png`;if(e==='affection'||e==='disdain')return`assets/${s==='classic'?'classic':s}-${e}.png`;return`assets/${s==='classic'?'':s+'-'}neutral.webp`}
function bondAsset(s){return bondSkins[s]||asset(s)}
function currentSkin(){try{return JSON.parse(localStorage.getItem('neko-classroom-v1')||'{}').skin||'classic'}catch{return'classic'}}
function log(text){data.logs.unshift(text);data.logs=data.logs.slice(0,5)}
function changeBond(delta,reason){const before=data.bond;data.bond=clamp(data.bond+delta);log(`${delta>=0?'＋':''}${data.bond-before} · ${reason}`);save();renderBond();window.dispatchEvent(new CustomEvent('neko-affection',{detail:{value:data.bond,delta:data.bond-before,reason}}));return data.bond-before}
function syncRewards(){if(data.bond>=100){data.unlockedSkins=[...new Set([...data.unlockedSkins,...Object.keys(rewardSkins)])];data.claimedMilestones=[70,80,90,95];save()}}
function renderBond(){syncRewards();const [name,desc]=stage(),slot=milestones.find(x=>data.bond>=x&&!data.claimedMilestones.includes(x));$('devBadge').hidden=!data.developerMode;document.body.classList.toggle('dev-mode',!!data.developerMode);$('bondBadge').textContent=data.bond;$('bondValue').textContent=data.bond;$('bondStage').textContent=name;$('bondDescription').textContent=desc;$('bondBar').style.width=data.bond+'%';$('bondEnergy').textContent=`${Math.max(0,3-data.actionsUsed)} / 3`;$('bondPortrait').src=bondAsset(currentSkin());$('bondBubble').textContent=data.bond<20?'这种程度，也想让我夸你吗？':data.bond>=70?'再靠近一点，我只讲给你听。':'今天也一起认真学习吧。';$('rewardUnlock').classList.toggle('unlocked',!!slot||data.bond>=100);$('rewardIcon').textContent=data.bond>=100?'✓':slot?'✦':'🔒';$('rewardTitle').textContent=data.bond>=100?'限定衣装全部收集完成':slot?`好感 ${slot} 奖励 · 任选一套`:'下一次限定衣装选择';const next=milestones.find(x=>data.bond<x);$('rewardHint').textContent=data.bond>=100?'最高好感已经解锁全部限定衣装':slot?'选择后永久保留，之后不能更换本次选择':next?`好感达到 ${next} 后可再选一套`:'好感 100 时解锁最后一套';$('rewardChoices').hidden=!slot;document.querySelectorAll('[data-reward-skin]').forEach(b=>b.disabled=data.developerMode||data.unlockedSkins.includes(b.dataset.rewardSkin));$('unlockedSkins').textContent=data.developerMode?'开发者模式：全部衣装已开放':data.unlockedSkins.length?'已收藏：'+data.unlockedSkins.map(x=>allSkinNames[x]).filter(Boolean).join(' · '):'尚未收藏限定衣装';$('bondLog').innerHTML=data.logs.map(x=>`<span>${x}</span>`).join('')}
function eligible(){return books[level].filter(w=>w.sentences?.some(s=>s.sentence&&s.translation&&new RegExp(`\\b${w.word.replace(/[.*+?^${}()|[\\]\\\\]/g,'\\$&')}\\b`,'i').test(s.sentence)))}
function shuffle(a){for(let i=a.length-1;i;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
function setMeta(type){$('practiceEyebrow').textContent=`${level.toUpperCase()} · SKILL LAB`;$('practiceTitle').textContent=`${level==='cet4'?'四级':'六级'}专项训练中心`;$('practiceType').textContent=type;$('practiceScore').textContent=`本级完成 ${data.practice[level]||0}`;$('practiceFeedback').textContent='';$('practiceNext').hidden=false;answered=false}
function complete(delta,reason){data.practice[level]=(data.practice[level]||0)+1;save();changeBond(delta,reason);$('practiceScore').textContent=`本级完成 ${data.practice[level]}`}
function renderReading(){setMeta('阅读 · 选词填空');const pool=eligible(),w=pool[Math.floor(Math.random()*pool.length)],sample=w.sentences.find(s=>new RegExp(`\\b${w.word.replace(/[.*+?^${}()|[\\]\\\\]/g,'\\$&')}\\b`,'i').test(s.sentence));question={w,sample};$('practicePrompt').textContent=sample.sentence.replace(new RegExp(`\\b${w.word.replace(/[.*+?^${}()|[\\]\\\\]/g,'\\$&')}\\b`,'i'),' ______ ');$('practiceSub').textContent='从四个选项中选择最适合句意和语法的单词。';$('practiceInput').hidden=true;$('practiceTools').replaceChildren();const choices=[w,...shuffle(pool.filter(x=>x.word!==w.word)).slice(0,3)];shuffle(choices);$('practiceOptions').innerHTML=choices.map((x,i)=>`<button data-read="${x.word}"><b>${'ABCD'[i]}</b><span>${x.word}</span></button>`).join('');$('practiceOptions').querySelectorAll('button').forEach(b=>b.onclick=()=>{if(answered)return;answered=true;const right=b.dataset.read===w.word;document.querySelectorAll('[data-read]').forEach(x=>{x.disabled=true;if(x.dataset.read===w.word)x.classList.add('correct');else if(x===b)x.classList.add('wrong')});$('practiceFeedback').innerHTML=`<strong>${right?'✓ 选对了':'↺ 再看一次语境'}</strong><br>${sample.sentence}<br>${sample.translation}`;complete(right?2:-1,right?'完成阅读题':'阅读题答错')})}
function renderTranslation(){setMeta('翻译 · 汉译英');const pool=eligible(),w=pool[Math.floor(Math.random()*pool.length)],sample=w.sentences[Math.floor(Math.random()*w.sentences.length)];question={w,sample};$('practicePrompt').textContent=sample.translation;$('practiceSub').textContent='把这句话译成英文。系统会检查核心词，并给出词库参考译文。';$('practiceOptions').replaceChildren();$('practiceInput').hidden=false;$('practiceInput').value='';$('practiceInput').placeholder='在这里输入英文译文…';$('practiceTools').innerHTML='<button id="submitTranslation">检查译文</button>';$('submitTranslation').onclick=()=>{if(answered)return;const input=$('practiceInput').value.toLowerCase(),stop=new Set(['this','that','with','from','have','were','been','their','there','would','could','should','about','into','than','then','when','what','your']);const keys=[...new Set(sample.sentence.toLowerCase().match(/[a-z]+/g)||[])].filter(x=>x.length>3&&!stop.has(x));const hit=keys.filter(x=>input.includes(x)),score=keys.length?hit.length/keys.length:0;answered=true;$('practiceFeedback').innerHTML=`<strong>${score>=.55?'✓ 核心意思基本到位':'△ 先对照关键词修改'}</strong><br>命中关键词：${hit.join('、')||'暂无'}<br><b>参考译文：</b>${sample.sentence}`;complete(score>=.55?3:-1,score>=.55?'完成翻译题':'翻译需要修改')};}
function renderWriting(){setMeta('写作 · 计时练习');const set=writing[level],p=set[Math.floor(Math.random()*set.length)],min=level==='cet4'?120:150,max=level==='cet4'?180:200;question={p,min,max};$('practicePrompt').textContent=p[0];$('practiceSub').textContent=p[1];$('practiceOptions').replaceChildren();$('practiceInput').hidden=false;$('practiceInput').value='';$('practiceInput').placeholder=`建议 ${min}–${max} 词：开头表明观点，中间给理由和例子，结尾收束。`;$('practiceTools').innerHTML=`<span id="writingTimer">00:00</span><span id="writingCount">0 / ${min} 词</span><button id="submitWriting">完成写作</button>`;timerStart=Date.now();clearInterval(timerId);timerId=setInterval(()=>{const s=Math.floor((Date.now()-timerStart)/1000);if($('writingTimer'))$('writingTimer').textContent=`${String(Math.floor(s/60)).padStart(2,'0')}:${String(s%60).padStart(2,'0')}`},1000);const count=()=>($('practiceInput').value.trim().match(/[A-Za-z]+(?:'[A-Za-z]+)?/g)||[]).length;$('practiceInput').oninput=()=>{$('writingCount').textContent=`${count()} / ${min} 词`};$('submitWriting').onclick=()=>{if(answered)return;answered=true;clearInterval(timerId);const n=count(),ok=n>=min;$('practiceFeedback').innerHTML=`<strong>${ok?'✓ 完成一篇限时作文':'△ 字数还不够'}</strong><br>结构自查：是否明确回应题目？是否有两个理由或例子？段落之间是否有连接词？结尾是否回扣观点？`;complete(ok?4:-1,ok?'完成写作练习':'写作未达建议字数')}}
function renderPractice(){document.querySelectorAll('[data-practice]').forEach(b=>b.classList.toggle('active',b.dataset.practice===mode));$('practiceInput').oninput=null;clearInterval(timerId);if(mode==='reading')renderReading();else if(mode==='translation')renderTranslation();else renderWriting()}
function open(view,newLevel){level=newLevel||level;if(view==='practice')renderPractice();if(view==='bond')renderBond()}
document.querySelectorAll('[data-practice]').forEach(b=>b.onclick=()=>{mode=b.dataset.practice;renderPractice()});$('practiceNext').onclick=renderPractice;
document.querySelectorAll('[data-bond-action]').forEach(b=>b.onclick=()=>{if(data.actionDay!==today()){data.actionDay=today();data.actionsUsed=0}if(data.actionsUsed>=3){$('bondBubble').textContent='今天的课后时间用完啦，明天再来找我。';return}const actions={praise:[4,'你认真地夸奖了小春。'],gift:[8,'猫爪饼干让她眼睛一亮。'],tease:[-6,'你故意在课堂上捣乱。'],ignore:[-9,'你转身冷落了她。']};data.actionsUsed++;const [delta,reason]=actions[b.dataset.bondAction];changeBond(delta,reason)});
function redeem(){const code=$('redeemCode').value.trim().toUpperCase(),feedback=$('redeemFeedback');feedback.className='';if(code==='666666'){data.developerMode=true;log('已开启开发者模式');save();renderBond();window.dispatchEvent(new CustomEvent('neko-unlock',{detail:{developer:true}}));feedback.textContent='开发者模式已开启，全部衣装可用。';feedback.classList.add('success');$('redeemCode').value='';return}if(code!=='SCUT888'){feedback.textContent='兑换码不正确，请检查后重试。';feedback.classList.add('error');return}if(!data.unlockedSkins.includes('scut')){data.unlockedSkins.push('scut');log('兑换领取「特别校服」');save();renderBond();window.dispatchEvent(new CustomEvent('neko-unlock',{detail:{skin:'scut'}}))}feedback.textContent='兑换成功！特别校服已永久加入衣橱。';feedback.classList.add('success');$('redeemCode').value=''}
$('redeemButton').onclick=redeem;$('redeemCode').onkeydown=e=>{if(e.key==='Enter'){e.preventDefault();redeem()}};
document.querySelectorAll('[data-reward-skin]').forEach(b=>b.onclick=()=>{const slot=milestones.find(x=>data.bond>=x&&!data.claimedMilestones.includes(x)),s=b.dataset.rewardSkin;if(!slot||data.unlockedSkins.includes(s))return;data.claimedMilestones.push(slot);data.unlockedSkins.push(s);log(`解锁限定衣装「${rewardSkins[s]}」`);save();renderBond();window.dispatchEvent(new CustomEvent('neko-unlock',{detail:{skin:s}}))});
window.addEventListener('neko-skin',e=>{$('bondPortrait').src=bondAsset(e.detail.skin)});
window.NekoModules={open,changeBond,affection:()=>data.bond,unlocked:s=>data.developerMode||(s==='scut'?data.unlockedSkins.includes('scut'):!rewardSkins[s]||data.unlockedSkins.includes(s)||data.bond>=100),renderBond};
renderBond();
})();
